    - name: Install {{pkag}} service
      action: yum pkg={{pkag}} state=present
      notify: Restart {{pkag}} service

    - name: copy yml playbook
      action: copy src=/home/ansible/tasks.yml dest=/home/ansible mode=777

    - name: copy a file from remote to remote
      action: copy remote_src=yes src=/home/ansible/gajodhar dest=/tmp mode=555

    - name: Add a user
      action: user name={{item}}
      with_items:
        - abhishek9999
        - megha9999

    - name: Unarchive a zip file
      action: unarchive src=/home/ansible/khajana.zip dest=/tmp mode=444
      when: ansible_os_family=='RedHat'

    - name: Unarchive a zip file
      action: unarchive src=/home/ansible/khajana1.zip dest=/tmp mode=400
      when: ansible_os_family=='Debian'

    - name: create a file
      action: file path=/tmp/touched state=touch mode=755

    - name: create a file
      action: file path=/tmp/world state=touch mode=755

    - name: copy content to a file
      action: copy content='Hello World, this is me' dest=/tmp/world mode=777


